# Generated by Django 5.2.4 on 2026-06-05 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(max_length=15)),
                ('Photo', models.FileField(upload_to='')),
                ('Place', models.CharField(max_length=50)),
                ('Post', models.CharField(max_length=50)),
                ('Pin', models.IntegerField()),
                ('Phone', models.BigIntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=500)),
                ('Priority', models.CharField(max_length=15)),
                ('Created_date', models.DateField()),
                ('Due_date', models.DateField()),
                ('Status', models.CharField(max_length=20)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_list.user_table')),
            ],
        ),
    ]
